events {}

http {
    server {
        listen 80;
        server_name fh.polban.studio;

        # Redirect HTTP to HTTPS
        return 301 https://$host$request_uri;
    }

    server {
	    listen 443 ssl;
	    server_name mfh.web.id;

	    ssl_certificate /etc/letsencrypt/live/mfh.web.id/fullchain.pem;
	    ssl_certificate_key /etc/letsencrypt/live/mfh.web.id/privkey.pem;

	    ssl_protocols TLSv1.2 TLSv1.3;
	    ssl_ciphers HIGH:!aNULL:!MD5;

        location ^~ /grafana/ {
            proxy_pass http://grafana:3000/grafana/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Prefix /grafana;
            proxy_http_version 1.1;
            proxy_buffering off;
        }

        location = /grafana {
            return 301 /grafana/;
        }

         location / {
              proxy_pass http://flask-api-secure:5000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_connect_timeout 1s;
              proxy_read_timeout 2s;
              proxy_send_timeout 2s;
              proxy_intercept_errors on;
              error_page 502 = @fallback;
          }

          location /prometheus/ {
              proxy_pass http://prometheus:9090/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_http_version 1.1;
              proxy_buffering off;
          }
    }
}
